---

db:
  image: mysql:5.6 
  environment:
    - MYSQL_ROOT_PASSWORD=mypassword
    - DNSDOCK_NAME=db1
    - DNSDOCK_IMAGE=db

mongo:
  image: mongo:2.6
 volumes: 
   - /var/devstack/mongo/data:/data

es:
 build: ../build/elasticsearch
  image: edxops/elasticsearch:v1
 volumes:
   - /tmp/elasticsearch/data:/es-data

memcache:
 image: memcached:1.4.24

forums:
 build: ../build/forums
 image: edxops/forums:v2 
 volumes:
   - /home/edward/Documents/git/edx/configuration:/configuration

nginx:
 build: ../build/nginx
    
rabbitmq:
 image: rabbitmq:3.5.3

xqueue:
  build: ../build/xqueue
  environment:
      - DNSDOCK_IMAGE=xqueue
 
edxapp:
 build: ../build/edxapp
