db:
  image: mysql:5.6 
  environment:
    - MYSQL_ROOT_PASSWORD=mypassword
    - DNSDOCK_NAME=db1
    - DNSDOCK_IMAGE=db

mongo:
  image: mongo:2.6
  volumes: 
    - /var/devstack/mongo/data:/data

es:
 build: ../build/elasticsearch
 volumes:
   - /tmp/elasticsearch/data:/es-data

memcache:
 image: memcached:1.4.24

forums:
 build: ../build/forums
 volumes:
   - ../../:/configuration
 links: 
   - db:lms-mysql.local.edx.org
   - mongo:lms-mongo.local.edx.org

nginx:
 build: ../build/nginx
 links:
   - lms:lms.local.edx.org
   - cms:cms.local.edx.org
    
rabbitmq:
 image: rabbitmq:3.5.3

xqueue:
  build: ../build/xqueue
  environment:
      - DNSDOCK_IMAGE=xqueue
 
lms:
 build: ../build/edxapp
 links: 
   - db:lms-mysql.local.edx.org
   - mongo:lms-mongo.local.edx.org
   - rabbitmq:lms-rabbitmq.local.edx.org
   - xqueue:xqueue.local.edx.org
   - es:lms-elasticsearch.local.edx.org
   - memcache:lms-memcache.local.edx.org
cms:
 build: ../build/edxapp
 links: 
   - db:cms-mysql.local.edx.org
   - mongo:cms-mongo.local.edx.org
   - xqueue:xqueue.local.edx.org
   - es:cms-elasticsearch.local.edx.org
   - rabbitmq:cms-rabbitmq.local.edx.org
   - memcache:cms-memcache.local.edx.org
gp:
 image: edxops/precise-common:v1
 volumes:
   - ../../:/configuration
 links: 
   - db:lms-mysql.local.edx.org
   - mongo:lms-mongo.local.edx.org
   - rabbitmq:lms-rabbitmq.local.edx.org
   - memcache:lms-memcache.local.edx.org
